Stars2/Areas/Admin/Controllers/USArmasController.cs
using Business.Business;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Stars2.Areas.Admin.Controllers
{
    public class USArmasController : Controller
    {
        // GET: Admin/USArmas
        public ActionResult Index()
        {
            var list = new ArmasBusiness().List();
            return View(list);
        }
        [HttpGet]
        public ActionResult Details(int id)
        {
            var arma = new ArmasBusiness().Get(id);
            return View(arma);
        }
    }
}

Stars2/Areas/Admin/Views/USArmas/Details.cshtml
@model Business.Mapping.Armas

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div class="det">
    <div class="imgdet">
        <img src="~/Content/Estilo/@(Model.ID)a.jpg" style="width:100%;height:70%" />
    </div>
    <div class="nomedescdet">
        <h4>@Html.DisplayFor(model => model.Nome)</h4>
        <p>@Html.DisplayFor(model => model.Descricao)</p>
    </div>
</div>
<br />
<a class="butedit" href="~/Admin/USArmas/Index">


    Voltar
</a>
<br />

Stars2/Areas/Admin/Views/USArmas/Index.cshtml
@model IEnumerable<Business.Mapping.Armas>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Armas</h2>
                     @foreach (var item in Model)
                     {                                                 
                        <a class="grid" href="@Url.Action("Details", "USArmas", new { id = item.ID })">
                            <div class="imagehome">
                            <div class="img_layer"></div>
                            <img src="~/Content/Estilo/@(item.ID)a.jpg" style="width:100%;height:82%;" />
                            </div>
                                <div class="edic">
                                <p class="parahome">@Html.DisplayFor(modelItem => item.Nome)</p>
                            </div>
                        </a>

                     } 
<br />