Stars2/Areas/Admin/Controllers/USVeiculosController.cs
using Business.Business;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Stars2.Areas.Admin.Controllers
{
    public class USVeiculosController : Controller
    {
        // GET: Admin/USVeiculos
        public ActionResult Index()
        {
            var list = new VeiculosBusiness().List();
            return View(list);
        }
        [HttpGet]
        public ActionResult Details(int id)
        {
            var veiculo = new VeiculosBusiness().Get(id);
            return View(veiculo);
        }
    }
}

Stars2/Areas/Admin/Views/USVeiculos/Details.cshtml
@model Business.Mapping.Veiculos

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div class="det">
    <div class="imgdet">
        <img src="~/Content/Estilo/@(Model.ID)v.jpg" style="width:100%;height:70%" />
    </div>
    <div class="nomedescdet">
        <h4>@Html.DisplayFor(model => model.Nome)</h4>
        <p>@Html.DisplayFor(model => model.Descricao)</p>
    </div>
</div>
<br />
<a class="butedit" href="~/Admin/USVeiculos/Index">


    Voltar
</a>

Stars2/Areas/Admin/Views/USVeiculos/Index.cshtml
@model IEnumerable<Business.Mapping.Veiculos>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Veiculos</h2>


@foreach (var item in Model)
{

    <a class="grid" href="@Url.Action("Details", "USVeiculos", new { id = item.ID })">
        <div class="imagehome">
        <div class="img_layer"></div>
        <img src="~/Content/Estilo/@(item.ID)v.jpg"/>
            </div>
        <div class="edic">
            <p class="parahome">@Html.DisplayFor(modelItem => item.Nome)</p>
        </div>
    </a>
}
<br />