Stars2/Areas/Admin/Controllers/USPersonagensController.cs
using Business.Business;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Stars2.Areas.Admin.Controllers
{
    public class USPersonagensController : Controller
    {
        // GET: Admin/USPersonagens
        public ActionResult Index()
        {
            var list = new PersonagensBusiness().List();
            return View(list);
        }
        [HttpGet]
        public ActionResult Details(int id)
        {
            var personagem = new PersonagensBusiness().Get(id);
            return View(personagem);
        }
    }
}

Stars2/Areas/Admin/Views/USPersonagens/Details.cshtml
@model Business.Mapping.Personagens

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div class="det">
    <div class="imgdet">
        <img src="~/Content/Estilo/@(Model.ID)p.jpg" style="width:100%;height:70%"/>
    </div>
    <div class="nomedescdet">
    <h4>@Html.DisplayFor(model => model.Nome)</h4>
    <p>@Html.DisplayFor(model => model.Descricao)</p>
     </div>
</div>
<br/>
   <a class="butedit" href="~/Admin/USPersonagens/Index">


   Voltar
   </a>
  

Stars2/Areas/Admin/Views/USPersonagens/Index.cshtml
@model IEnumerable<Business.Mapping.Personagens>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Personagens</h2>
@foreach (var item in Model)
{

    <a class="grid" href="@Url.Action("Details", "USPersonagens", new { id = item.ID })">
        <div class="imagehome">
        <div class="img_layer"></div>
        <img src="~/Content/Estilo/@(item.ID)p.jpg" style="width:100%;height:82%;" />
        </div>
        <div class="edic">
            <p class="parahome">@Html.DisplayFor(modelItem => item.Nome)</p>
        </div>
    </a>
}

<br />